- id: jenkinsfile-lint
  name: jenkinsfile-lint
  description: ensures Jenkinsfile is valid
  entry: jenkinsfilelint
  language: python
  types: [file]
  files: ^.*(Jenkinsfile.*|.*\.groovy)$
  require_serial: true
