- id: jenkinsfilelint
  name: jenkinsfilelint
  description: Lint Jenkinsfiles and Groovy files.
  entry: jenkinsfilelint
  language: python
  types: [file]
  files: ^.*(Jenkinsfile.*|.*\.groovy)$
  require_serial: true
